<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CertifyDocx.Core</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>Off</OptionInfer>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CertifyDocx.Core.Tests" />
  </ItemGroup>

</Project>
